### ISSUE TITLE
Mismatched names

### ISSUE THREAD

**Issue by davidskeck** [nsmryan/serial_passthrough#1]
Should OUTSTREAM be OUTPORT?

https://github.com/nsmryan/serial_passthrough/blob/33c3714cd10933e94115dffdc79c1b1adff82e40/src/main.rs#L26

https://github.com/nsmryan/serial_passthrough/blob/33c3714cd10933e94115dffdc79c1b1adff82e40/src/main.rs#L64

Also, apparently I love following you around and adding issues to your code 😛

**Comment by nsmryan** [comment]
Indeed! I have fixed this in the latest commit.

Thanks for pointing this out!
